# Generated by Django 3.2.6 on 2022-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=150)),
                ('Blog_Date', models.DateField(auto_now_add=True)),
                ('Blog_Desc', models.TextField(max_length=3000)),
                ('Blog_Image', models.ImageField(upload_to='Image')),
            ],
        ),
    ]
